services:
  - type: web
    name: capital-multiplier
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      uvicorn app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: CHAT_ID
        sync: false

      - key: WEBHOOK_SECRET
        sync: false
